name: Drupal-custom-module-checking
on: push
jobs:
  Custom-module-checking-phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Install PHP CodeSniffer
        run: |
          composer require --dev dealerdirect/phpcodesniffer-composer-installer
          composer require --dev drupal/coder
      - name: Current location check
        run: |
          pwd
          ls -la
      - name: Check coding standarts
        run: |
          vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml ./web/module/custom
