name: Drupal-custom-module-checking
on: push
jobs:
  Custom-module-checking-phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3       

      - name: Install PHP CodeSniffer
        run: |
          composer global require drupal/coder
          composer global show -P

      - name: Check coding standarts
        run: | 
          ./vendor/bin/phpcs --config-set installed_paths vendor/drupal/coder/coder_sniffer
          ./vendor/bin/phpcs --standard=Drupal --extensions=php,module,inc,install,test,profile,theme,css,info,txt,md,yml ./web/modules/custom
